---
- hosts: workstation

  tasks:
    - name: install git
      homebrew: name=git state=latest update_homebrew=yes

    - name: check if git global settings are already set
      command: git config --global --list
      ignore_errors: yes
      register: git_global_settings

    - name: setup git user name
      command: git config --global user.name "{{ git.user.fullname }}"
      when: git_global_settings.rc == 128

    - name: setup git user email
      command: git config --global user.email "{{ git.user.email }}"
      when: git_global_settings.rc == 128 

