- name: Build my Workstation <3 <3 <3 :)
  hosts: workstation
  tasks:

################################################
# First things
################################################

  - name: update homebrew formulaes and upgrade already installed software
    homebrew: update_homebrew=yes upgrade_all=yes
    tags: homebrew_upgrade_all
    when: battleschool.homebrew.upgrade_all

  - include: home.yml
    tags: home

################################################
# Base Tools
################################################

  - include: homebrew_extras.yml
    tags: homebrew_extras
    when: battleschool.homebrew_extras

  - include: git.yml
    tags: git
    when: battleschool.git
    vars:
      git:
        user:
          fullname: 'Gilles Cornu'
          email:    'git@gilles.cornu.name'

  - include: nodejs.yml
    tags: nodejs
    when: battleschool.nodejs
    vars:
      nodejs:
        global_packages:
          - bower
          - grunt-cli
          - git-travis
          - yo

  - include: sourcetree.yml
    tags: sourcetree
    when: battleschool.sourcetree

################################################
# Virtualization Tools
################################################

  - include: virtualbox.yml
    tags: virtualbox
    when: battleschool.virtualbox
    vars:
      virtualbox:
        version: 4.3.20
        build:   96996

  - include: vagrant.yml
    tags: vagrant
    when: battleschool.vagrant
    vars:
      vagrant:
        version: 1.7.1

################################################
# IDE, Editor, ...
################################################

  - include: intellij_idea.yml
    tags: intellij_idea
    when: battleschool.intellij_idea
